<a href="https://colab.research.google.com/github/saitej12345678/minig/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/drive/MyDrive/students_placement_data.csv")
df.head()

,Roll No,Gender,Section,SSC Percentage,inter_Diploma_percentage,B.Tech_percentage,Backlogs,registered_for_ Placement_Training,placement status
0,1,M,A,87.3,65.3,40.00,18,NO,Not placed
1,2,F,A,89.0,92.4,21.20,0,yes,Placed
2,3,F,A,67.0,40.2,NaN,13,yes,Not placed
3,4,M,A,71.0,70.4,36.47,17,yes,Not placed
4,5,M,A,44.0,65.5,42.52,17,yes,Not placed

In [ ]:
df["SSC Percentage"]=df["SSC Percentage"].replace(to_replace=np.nan,value=np.mean(df["SSC Percentage"]))
df.head()

,Roll No,Gender,Section,SSC Percentage,inter_Diploma_percentage,B.Tech_percentage,Backlogs,registered_for_ Placement_Training,placement status
0,1,M,A,87.3,65.3,40.00,18,NO,Not placed
1,2,F,A,89.0,92.4,21.20,0,yes,Placed
2,3,F,A,67.0,40.2,NaN,13,yes,Not placed
3,4,M,A,71.0,70.4,36.47,17,yes,Not placed
4,5,M,A,44.0,65.5,42.52,17,yes,Not placed

In [ ]:
print(df['Gender'].value_counts())
print(df['Section'].value_counts())
print(df['placement status'].value_counts())
print(df['registered_for_ Placement_Training'].value_counts())

M    68
F    49
Name: Gender, dtype: int64
A    60
B    57
Name: Section, dtype: int64
Not placed    78
Placed        39
Name: placement status, dtype: int64
yes    67
NO     49
Name: registered_for_ Placement_Training, dtype: int64

In [ ]:
import plotly.express as px
cut_counts=df['Gender'].value_counts()
fig=px.bar(x=cut_counts.index,y=cut_counts.values)
fig.show()

In [ ]:
pd.crosstab(index=df['Gender'],columns=df['placement status'])

placement status  Not placed  Placed
Gender
F                         20      29
M                         58      10

In [ ]:
pd.pivot_table(df, values='B.Tech_percentage',index='Gender',columns='placement status',aggfunc=np.mean)

placement status  Not placed     Placed
Gender
F                  66.360526  73.531379
M                  54.825345  69.574000